-- ============================================================
-- V1 - Application Schema (H2 + DB2 compatible)
-- ============================================================

CREATE TABLE ROLES (
    ID         BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME       VARCHAR(50) NOT NULL
);

CREATE UNIQUE INDEX UQ_ROLES_NAME ON ROLES (NAME);

CREATE TABLE USERS (
    ID                       BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USERNAME                 VARCHAR(50)  NOT NULL,
    EMAIL                    VARCHAR(150) NOT NULL,
    PASSWORD                 VARCHAR(255) NOT NULL,
    ENABLED                  SMALLINT     NOT NULL DEFAULT 1,
    ACCOUNT_NON_EXPIRED      SMALLINT     NOT NULL DEFAULT 1,
    ACCOUNT_NON_LOCKED       SMALLINT     NOT NULL DEFAULT 1,
    CREDENTIALS_NON_EXPIRED  SMALLINT     NOT NULL DEFAULT 1,
    MFA_ENABLED              SMALLINT     NOT NULL DEFAULT 0,
    MFA_SECRET               VARCHAR(64),
    -- Social login provider info (null for local users)
    PROVIDER                 VARCHAR(20),
    PROVIDER_ID              VARCHAR(255),
    CREATED_AT               TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL, -- avoid DB2-specific `WITH DEFAULT` for H2 compatibility
    UPDATED_AT               TIMESTAMP
);

CREATE UNIQUE INDEX UQ_USERS_USERNAME ON USERS (USERNAME);
CREATE UNIQUE INDEX UQ_USERS_EMAIL    ON USERS (EMAIL);

CREATE TABLE USER_ROLES (
    USER_ID BIGINT NOT NULL,
    ROLE_ID BIGINT NOT NULL,
    CONSTRAINT PK_USER_ROLES PRIMARY KEY (USER_ID, ROLE_ID),
    CONSTRAINT FK_UR_USER    FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON DELETE CASCADE,
    CONSTRAINT FK_UR_ROLE    FOREIGN KEY (ROLE_ID) REFERENCES ROLES (ID) ON DELETE CASCADE
);

CREATE TABLE PASSWORD_RESET_TOKENS (
    ID          BIGINT       GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TOKEN       VARCHAR(100) NOT NULL,
    USER_ID     BIGINT       NOT NULL,
    EXPIRY_DATE TIMESTAMP    NOT NULL,
    USED        SMALLINT     NOT NULL DEFAULT 0,
    CREATED_AT  TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL, -- avoid DB2-specific `WITH DEFAULT` for H2 compatibility
    CONSTRAINT FK_PRT_USER FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON DELETE CASCADE
);

CREATE UNIQUE INDEX UQ_PRT_TOKEN ON PASSWORD_RESET_TOKENS (TOKEN);
